### ISSUE TITLE
Unused dependecies

### ISSUE THREAD

**Issue by PetersonJFP** [atados/ovp-client-module-base#9]
Essas são as dependencias que n são importadas em arquivo nenhum, algumas são dependencias de dependencias mas vale pensar se n tem nada ai q n ta mais sendo usado e ta fazendo peso a mais em vão

```
@formatjs/intl-relativetimeformat
@maxmind/geoip2-node
apollo-link
apollo-link-http
apollo-link-ws
body-parser
copy
geoip-lite
immutable
intl-pluralrules
maxmind
react-string-replace
subscriptions-transport-ws
```

**Comment by vinpac** [comment]
Mergeei a remoção dessas dependências
